name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Format
        run: nix-shell --pure --run "cargo fmt && git diff --exit-code"

      - name: Lint
        run: nix-shell --pure --run "cargo clippy -- -D warnings"
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: nix-shell --pure --run "cargo build"

    - name: Test
      run: nix-shell --pure --run "cargo test"
