name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix-shell --pure --run "cargo build"
      - name: Test
        run: nix-shell --pure --run "cargo test"
      - name: Format
        run: nix-shell --pure --run "cargo fmt && git diff --exit-code"
      - name: Lint
        run: nix-shell --pure --run "cargo clippy -- -D warnings"
